#한글깨짐 방지로 한글을 유니코드로 변환
myboot.name = MySpring TEST

#log level(운영 환경과 다르게 설정) : debug
logging.level.com.basic.myspringboot=debug


#h2 db에 대한 정보 setter
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa