myboot.name=MySpring PROD

#log level : info
logging.level.com.basic.myspringboot=info

#mariadb
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/boot_db
spring.datasource.username=boot
spring.datasource.password=boot
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

#hibernate
#validate는 새로 추가한 column이 즉시 테이블에 반영이 아닌 구조를 비교해 있으면 통과 없으면 에러(즉, 검증하는 역할이고 테이블 스키마가 있어야함.)
#validate는 테이블이 만들어지고 구조가 있어야지 검증해서 log에 찍히고 테이블이 없을경우도 에러남
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect